# Generated by Django 4.1.7 on 2023-03-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_author_project_completed_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="desctription",
            new_name="description",
        ),
    ]
