# Generated by Django 4.1.7 on 2023-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_desctription_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visiblity",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=32,
            ),
        ),
    ]
