# Generated by Django 4.1.7 on 2023-04-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_visiblity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="visiblity",
            new_name="visibility",
        ),
    ]
