# Generated by Django 4.1.7 on 2023-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_rename_visiblity_project_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("published", "Published"), ("draft", "Draft")],
                default="draft",
                max_length=128,
                null=True,
            ),
        ),
    ]
