# Generated by Django 4.1.5 on 2023-02-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("book", "0004_book_project_chapter_book_alter_chapter_section_and_more"),
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="book",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.book",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="world",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
    ]
