# Generated by Django 4.1.7 on 2023-03-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_name_revision_notes_draft"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genere",
            new_name="genre",
        ),
    ]
