# Generated by Django 4.1.7 on 2023-04-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worlds", "0002_world_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="world",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="worlds.world",
            ),
        ),
        migrations.AddField(
            model_name="religions",
            name="world",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="worlds.world",
            ),
        ),
    ]
