# Generated by Django 4.1.5 on 2023-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_author_section_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("section", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("book", "order")},
        ),
    ]
