# Generated by Django 4.1.5 on 2023-02-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("book", "0003_chapter_status_alter_chapter_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="book",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.book",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.section",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Publish"),
        ),
    ]
