# Generated by Django 4.1.5 on 2023-02-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_book_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="book",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.book",
            ),
        ),
    ]
